version: '3.9'

services:

  maxit:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: maxit
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_maxit
    ports:
      - "8083:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - maxit
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_maxit
    restart: always
    environment:
      POSTGRES_DB: remediation
      POSTGRES_USER: maxit_user
      POSTGRES_PASSWORD: secretpass
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5436"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_maxit
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: khadijafall@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5052:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
